[workspace]
members = [
    "doradb-datatype",
    "doradb-catalog", 
    "doradb-sql",
    "doradb-expr",
    "doradb-compute", 
    "doradb-plan",
    "doradb-protocol",
    "doradb-storage",
    "doradb-server",
    "doradb-tpch-tests"
]
resolver = "2"
exclude = ["doradb-bench"]

[profile.release]
debug = true
