[workspace]
members = [
    "xngin-datatype",
    "xngin-catalog", 
    "xngin-frontend",
    "xngin-expr",
    "xngin-compute", 
    "xngin-index",
    "xngin-plan",
    "xngin-protocol",
    "xngin-storage",
    "xngin-runtime",
    "xngin-tpch-tests"
]
exclude = ["xngin-bench"]
