use super::sys::GC_BUCKETS;
use crate::buffer::PoolGuards;
use crate::catalog::{Catalog, SilentWatermarkObject};
use crate::error::{Error, InternalError, Result};
use crate::id::{PageID, RowID, TableID, TrxID};
use crate::log::block_group::TrxLog;
use crate::log::redo::{DDLRedo, RedoHeader, RedoLogs, RedoTrxKind, RowRedo, RowRedoKind};
use crate::table::NoTrxUpsertChange;
use crate::trx::{PreparedTrx, PreparedTrxPayload};
use error_stack::Report;
use std::mem;

/// One ordered row-page prefix retired by a successful table checkpoint.
#[derive(Debug, Eq, PartialEq)]
pub(crate) struct RetiredRowPageBatch {
    /// Owning user table.
    pub(crate) table_id: TableID,
    /// Inclusive start of the retired contiguous RowID range.
    pub(crate) start_row_id: RowID,
    /// Exclusive end of the retired contiguous RowID range.
    pub(crate) end_row_id: RowID,
    /// Row pages in their canonical RowID order.
    pub(crate) page_ids: Box<[PageID]>,
}

impl RetiredRowPageBatch {
    /// Creates one checkpoint retirement descriptor.
    #[inline]
    pub(crate) fn new(
        table_id: TableID,
        start_row_id: RowID,
        end_row_id: RowID,
        page_ids: Box<[PageID]>,
    ) -> Self {
        Self {
            table_id,
            start_row_id,
            end_row_id,
            page_ids,
        }
    }
}

/// SysTrx is a special kind of transaction only used for system
/// operations. Its effect is immediately visible for other
/// transactions and it can not rollback.
pub(crate) struct SysTrx {
    pub(super) redo: RedoLogs,
    pub(super) retired_row_pages: Option<RetiredRowPageBatch>,
}

impl SysTrx {
    /// Return accumulated redo for focused system-transaction tests.
    #[cfg(test)]
    #[inline]
    pub(crate) fn redo(&self) -> &RedoLogs {
        &self.redo
    }

    /// Record creation of a row page in this system transaction's redo payload.
    #[inline]
    pub(crate) fn create_row_page(
        &mut self,
        table_id: TableID,
        page_id: PageID,
        start_row_id: RowID,
        end_row_id: RowID,
    ) {
        debug_assert!(self.redo.ddl.is_none());
        // Actual row page is generated by block index and buffer pool.
        // Here we record page info in logging system for recovery.
        self.redo.ddl.replace(Box::new(DDLRedo::CreateRowPage {
            table_id,
            page_id,
            start_row_id,
            end_row_id,
        }));
    }

    /// Record publication of one durable user-table checkpoint root.
    #[inline]
    pub(crate) fn record_data_checkpoint(
        &mut self,
        table_id: TableID,
        pivot_row_id: RowID,
        checkpoint_ts: TrxID,
    ) {
        debug_assert!(self.redo.ddl.is_none());
        self.redo.ddl.replace(Box::new(DDLRedo::DataCheckpoint {
            table_id,
            pivor_row_id: pivot_row_id,
            checkpoint_ts,
        }));
    }

    /// Records the one row-page prefix retired by this checkpoint transaction.
    #[inline]
    pub(crate) fn retire_row_pages(&mut self, batch: RetiredRowPageBatch) {
        debug_assert!(self.retired_row_pages.is_none());
        self.retired_row_pages = Some(batch);
    }

    /// Monotonically update the live silent-watermark mirror and record logical redo.
    pub(crate) async fn upsert_silent_watermark(
        &mut self,
        catalog: &Catalog,
        guards: &PoolGuards,
        watermark: SilentWatermarkObject,
    ) -> Result<()> {
        match self.redo.ddl.as_deref() {
            None => {
                self.redo
                    .ddl
                    .replace(Box::new(DDLRedo::TableReplaySilentWatermark {
                        table_id: watermark.table_id,
                    }));
            }
            Some(DDLRedo::TableReplaySilentWatermark { table_id })
                if *table_id == watermark.table_id => {}
            Some(existing) => {
                return Err(Error::from(
                    Report::new(InternalError::Generic).attach(format!(
                        "silent watermark system transaction has incompatible DDL redo: existing={existing:?}, table_id={}",
                        watermark.table_id
                    )),
                ));
            }
        }
        let watermarks = catalog.storage.table_replay_silent_watermarks();
        let catalog_table_id = watermarks.table_id();
        let redo = &mut self.redo;
        watermarks
            .upsert_no_trx(guards, &watermark, |change| {
                let entry = match change {
                    NoTrxUpsertChange::Inserted {
                        page_id,
                        row_id,
                        vals,
                    } => RowRedo {
                        page_id,
                        row_id,
                        kind: RowRedoKind::Insert(vals),
                    },
                    NoTrxUpsertChange::Updated {
                        page_id,
                        row_id,
                        key,
                        cols,
                    } => RowRedo {
                        page_id,
                        row_id,
                        kind: RowRedoKind::UpdateByPrimaryKey(key, cols),
                    },
                };
                redo.insert_dml(catalog_table_id, entry);
            })
            .await
    }

    /// Prepare this transaction for commit.
    #[inline]
    pub(crate) fn prepare(mut self) -> PreparedTrx {
        let redo_bin = if self.redo.is_empty() {
            None
        } else {
            Some(TrxLog::new(
                RedoHeader {
                    cts: TrxID::new(0),
                    trx_kind: RedoTrxKind::System,
                },
                mem::take(&mut self.redo),
            ))
        };
        PreparedTrx {
            redo_bin,
            payload: self.retired_row_pages.take().map(|retired_row_pages| {
                PreparedTrxPayload::System(SysTrxPayload {
                    gc_no: retirement_gc_no(retired_row_pages.table_id),
                    retired_row_pages,
                })
            }),
            attachment: None,
            lock_manager: None,
            lock_state: None,
        }
    }
}

/// System transaction GC payload carried unchanged through ordered commit.
pub(crate) struct SysTrxPayload {
    pub(super) gc_no: usize,
    pub(super) retired_row_pages: RetiredRowPageBatch,
}

impl SysTrxPayload {
    #[inline]
    pub(super) fn is_empty(&self) -> bool {
        false
    }
}

/// Returns the deterministic GC bucket for one table's retirement payloads.
#[inline]
pub(crate) fn retirement_gc_no(table_id: TableID) -> usize {
    (table_id.as_u64() % GC_BUCKETS as u64) as usize
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sys_gc_prepare_uses_system_payload_variant() {
        let mut sys_trx = SysTrx {
            redo: RedoLogs::default(),
            retired_row_pages: None,
        };
        sys_trx.record_data_checkpoint(TableID::new(7), RowID::new(11), TrxID::new(13));
        sys_trx.retire_row_pages(RetiredRowPageBatch::new(
            TableID::new(7),
            RowID::new(3),
            RowID::new(11),
            vec![PageID::new(17)].into_boxed_slice(),
        ));
        let mut prepared = sys_trx.prepare();
        assert!(matches!(
            prepared.payload.as_ref(),
            Some(PreparedTrxPayload::System(SysTrxPayload {
                gc_no,
                retired_row_pages,
            })) if *gc_no == retirement_gc_no(TableID::new(7))
                && retired_row_pages.page_ids.as_ref() == [PageID::new(17)]
        ));
        prepared.redo_bin.take();
        prepared.payload.take();
    }

    #[test]
    fn test_retirement_gc_no_is_table_affine() {
        let table_id = TableID::new(91);
        assert_eq!(retirement_gc_no(table_id), retirement_gc_no(table_id));
        assert_eq!(
            retirement_gc_no(table_id),
            retirement_gc_no(TableID::new(
                table_id.as_u64() + super::super::sys::GC_BUCKETS as u64,
            ))
        );
    }
}
