use crate::id::{PageID, RowID, TableID, TrxID};
use crate::trx::PreparedTrx;
use crate::trx::log_replay::TrxLog;
use crate::trx::redo::{DDLRedo, RedoHeader, RedoLogs, RedoTrxKind};
use std::mem;

/// SysTrx is a special kind of transaction only used for system
/// operations. Its effect is immediately visible for other
/// transactions and it can not rollback.
pub(crate) struct SysTrx {
    pub(super) redo: RedoLogs,
}

impl SysTrx {
    #[inline]
    pub(crate) fn create_row_page(
        &mut self,
        table_id: TableID,
        page_id: PageID,
        start_row_id: RowID,
        end_row_id: RowID,
    ) {
        debug_assert!(self.redo.ddl.is_none());
        // Actual row page is generated by block index and buffer pool.
        // Here we record page info in logging system for recovery.
        self.redo.ddl.replace(Box::new(DDLRedo::CreateRowPage {
            table_id,
            page_id,
            start_row_id,
            end_row_id,
        }));
    }

    /// Prepare this transaction for commit.
    #[inline]
    pub(super) fn prepare(mut self) -> PreparedTrx {
        let redo_bin = if self.redo.is_empty() {
            None
        } else {
            Some(TrxLog::new(
                RedoHeader {
                    cts: TrxID::new(0),
                    trx_kind: RedoTrxKind::System,
                },
                mem::take(&mut self.redo),
            ))
        };
        PreparedTrx {
            redo_bin,
            payload: None,
            session: None,
            lock_manager: None,
            lock_state: None,
        }
    }
}
