name = "non-unique full-table deletion"
engine_defaults = "engine-defaults.toml"

[[phase]]
workload = { type = "create-table", index = "non-unique" }

[[phase]]
workload = { type = "insert-rand", num = 10000, seed = 42, batch_size = 100 }

[[phase]]
kind = "benchmark"
workload = { type = "delete-all" }
