name = "non-unique update-all"
engine_defaults = "engine-defaults.toml"

[[phase]]
workload = { type = "create-table", index = "non-unique" }

[[phase]]
workload = { type = "insert-rand", num = 10000, batch_size = 100, value_size = "128 B", seed = 42 }

[[phase]]
kind = "benchmark"
warmup_runs = 0
measured_runs = 1
workload = { type = "update-all", seed = 42, change_key = false, value_size = "128 B" }
