[nextest-version]
required = "0.9.100"

[profile.default]
slow-timeout = { period = "10s", terminate-after = 1, grace-period = "0s" }
global-timeout = "15s"
fail-fast = true

[profile.ci-default-features]
fail-fast = false

[profile.ci-default-features.junit]
path = "junit.xml"
report-name = "doradb-storage-default-features"

[profile.ci-no-default-features]
fail-fast = false

[profile.ci-no-default-features.junit]
path = "junit.xml"
report-name = "doradb-storage-no-default-features"
