[nextest-version]
required = "0.9.100"

[profile.default]
slow-timeout = { period = "10s", terminate-after = 1, grace-period = "0s" }
global-timeout = "30s"
fail-fast = true

[profile.ci]
fail-fast = false

[profile.ci.junit]
path = "junit.xml"
report-name = "doradb-storage"
